services:
  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    ports:
      - "4000:4000"
    environment:
      GATEWAY_PORT: 4000
      UPSTREAM_URL: http://fake-api:5000
      MONGO_URL: mongodb://mongo:27017/sentinel
      REDIS_URL: redis://redis:6379
      ADMIN_TOKEN: dev-admin-token
      API_KEY_PEPPER: dev-api-key-pepper
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
      fake-api:
        condition: service_started

  fake-api:
    build: ./apps/fake-api
    ports:
      - "5000:5000"
    environment:
      FAKE_API_PORT: 5000

  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    environment:
      MONGO_URL: mongodb://mongo:27017/sentinel
      REDIS_URL: redis://redis:6379
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy

  dashboard:
    build: ./apps/dashboard
    ports:
      - "3000:3000"
    environment:
      VITE_GATEWAY_URL: http://localhost:4000
      VITE_ADMIN_TOKEN: dev-admin-token
    depends_on:
      gateway:
        condition: service_started

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
